[project]
name = "ai-engineer-training"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "bs4>=0.0.2",
    "google-adk>=1.18.0",
    "google-genai>=1.47.0",
    "openpyxl>=3.1.5",
    "python-dateutil>=2.9.0.post0",
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
]
